name: vrsstranslinkcompany
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  charts_flutter_new: ^0.12.0
  get: ^4.6.5
  dio:
  shared_preferences:
  google_maps_flutter:
  google_maps_flutter_web:
  multi_dropdown: ^2.1.4
  flutter_screenutil: ^5.9.3
  flutter_polyline_points:
  flutter_dropzone:
  dotted_border:
  file_picker:
  http:
  geocoding:
  intl:
  fl_chart:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
